Repository hashhavoc/teller, pull requests merged in 2024-04, with the labels that each got.

#3 Add fileoutput
  internal/commands/wallet/wallet.go
Labels: enhancement

#6 Sync transactions
  README.md
  internal/commands/commands.go
  internal/commands/transactions/structs.go
  internal/commands/transactions/transactions.go
Labels: enhancement, Review effort [1-5]: 3

#8 update readme to help with onboarding
  .gitignore
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#10 update dockerfile to do its own building
  Dockerfile
Labels: enhancement
